server:
  port: 7002

spring:
  application:
    name: spring-cloud-eureka

eureka:
  server:
    eviction-interval-timer-in-ms: 5000
#    enable-self-preservation: false
  instance:
    hostname: Eureka7002 #eureka 服务端的实例名称
    instanceId: ${eureka.instance.hostname}
    prefer-ip-address: true     #访问路径可以显示IP地址
  client:
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://Eureka7000:7003/eureka/,http://Eureka7001:7001/eureka/