server:
  port: 9100

spring:
  application:
    name: micro-consumer-dept

user:
  userServicePath:  http://MICRO-PROVIDER-DEPT
#  http://localhost:8001

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://Eureka-7000:7000/eureka/,http://Eureka-7001:7001/eureka/,http://Eureka-7002:7002/eureka/
  instance:
    instanceId: ${spring.application.name}_${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30 #租期更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 90 #租期到期时间（默认90秒）