server:
  port: 8066

#person:
#  id: 1
#  name: test-person1
#  age: 25
#  work: manage
#  boss: false
#  birth: 1993/11/07
#  maps: {k1: v1, k2: v2}
#  lists:
#    - lisi
#    - zhangsan
#  dog:
#    name: 博美
#    age: 3