server:
  port: 8088

spring:
  application:
    name: micro-zuul-api-gateway

zuul:
  #prefix: /eric
  #“逗号,”作为分隔符
  #ignored-services: spring-cloud-eureka

  #ignored-services: "*"
  routes:
    micro-provider-dept-test: /pro-dept-test/**
    prodept:
      serviceId: micro-provider-dept
      path: /pro-dept/**
    test-route-name:
      serviceId: micro-test-route-name
      path: /test-route-name/**


management:
  security:
    enabled: false

eureka:
  client:
    service-url: #客户端注册进eureka服务列表内
      defaultZone: http://Eureka7000:7003/eureka/,http://Eureka7001:7001/eureka/,http://Eureka7002:7002/eureka/
  instance:
    hostname: api-gateway
    instanceId: ${eureka.instance.hostname}
    prefer-ip-address: true     #访问路径可以显示IP地址


info:
  app.name: micro-maven-practise
  company.name: eric
  build.artifactId: $project.artifactId$
  build.version: $project.version$