server:
  port: 80

spring:
  application:
    name: micro-consumer-dept-feign

feign:
  hystrix:
    enabled: true

user:
  userServicePath:  http://MICRO-PROVIDER-DEPT
#  http://localhost:8001

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://Eureka7000:7000/eureka/,http://Eureka7001:7001/eureka/,http://Eureka7002:7002/eureka/
  instance:
    instanceId: ${spring.application.name}_${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10 #租期更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 30

