server:
  port: 7510

spring:
  application:
    name: micro-hystrix-turbine

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://Eureka7000:7003/eureka/,http://Eureka7001:7001/eureka/,http://Eureka7002:7002/eureka/
  instance:
      instanceId: ${spring.application.name}_${server.port}
      prefer-ip-address: true
turbine:
  appConfig: MICRO-CONSUMER-DEPT-FEIGN
  cluster-name-expression: "'default'"
