server:
  port: 7600

spring:
  application:
    name:  micro-config-server
  cloud:
    config:
      server:
        git:
            uri: git@github.com:jia1102/spring-cloud-config-practise.git #GitHub上面的git仓库名字
            username: jia1102
            password: ljch19851213
#######################################################
#          uri: https://github.com/jia1102/spring-cloud-config-practise.git
#######################################################
#          uri: http://10.10.8.108/liujiachuan/micro-maven.git/
#          search-paths: micro-config-repo
#          username: liujiachuan
#          password: Ljch19851213!
          # force-pull: true
          # default-label: ${CONFIG_GIT_BRANCH:develop}
        health:
          repositories:
            a-client:
              label: master
              name: micro-config-client
              profiles: test