spring:
  application:
    name: spring-cloud-eureka

--- #Eureka7001
server:
  port: 7001

eureka:
  server:
    evictionIntervalTimerInMs: 5000
#    enable-self-preservation: false
  instance:
    hostname: Eureka7001 #eureka 服务端的实例名称
    instanceId: ${eureka.instance.hostname}
#    prefer-ip-address: true #访问路径可以显示IP地址
#    appname: 7001AppName
  client:
#    register-with-eureka: false     #false表示不向注册中心注册自己。
#    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://Eureka7000:7003/eureka/,http://Eureka7002:7002/eureka/

--- #Eureka7000